name: Deploy stack on aws
on: 
  push:
    branches:
      - main  # when every any code to pushed to main

jobs: # multi jobs to perform steps
  deply:
    runs-on: ubuntu-latest # from azure pool
    steps: # steps to setup cdk and run code
    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with: 
        node-version: '20'

    - name: checkout git repo code to vm 
      uses: actions/checkout@v2 

    - name: verify code in vm 
      run: ls 

    - name: install dependecies
      run: | 
        cd sc-bestway-d4
        npm install 
        npm install -g aws-cdk 

    - name: complie code 
      run: |
        cd sc-bestway-d4
        cdk synth 

    - name: deploy cdk in aws account 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.REGION }}
      run: |
        cd sc-bestway-d4
        cdk deploy Scec2allD4Stack --require-approval never

jobs: # multi jobs to perform steps
  deply:
    runs-on: ubuntu-latest # from azure pool
    steps: # steps to setup cdk and run code
    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with: 
        node-version: '20'

    - name: checkout git repo code to vm 
      uses: actions/checkout@v2 

    - name: verify code in vm 
      run: ls 

    - name: install dependecies
      run: | 
        cd sc-bestway-d4
        npm install 
        npm install -g aws-cdk 

    - name: complie code 
      run: |
        cd sc-bestway-d4
        cdk synth 

    - name: deploy cdk in aws account 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.REGION }}
      run: |
        cd sc-bestway-d4
        cdk deploy ScBestwayD4Stack --require-approval never
